# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0
comboTime: 25


# the rest of the config defines the layers with their bindings
layers:
# the first layer is active at start
- name: initial
  bindings:
    a+o: layer mouse
# a layer for mouse movement
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: false
  enterCommand: "notify-send 'mouse layer entered'"
  exitCommand: "notify-send 'mouse layer exited'"
  bindings:
    # quit mouse layer
    q: layer initial
    # keep the mouse layer active
    space: layer mouse
    s: move  1  0
    a: move -1  0
    r: move  0  1
    w: move  0 -1
    f: scroll up
    t: scroll down
    leftalt: speed 4.0
    l: speed 0.3
    capslock: speed 0.1
    n: button left
    u: button middle
    e: button right
